FROM python:3.9

# Set the working directory to /app
WORKDIR /app


COPY requirements.txt /app
COPY api.py /app

RUN pip install -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000


# Run app.py when the container launches
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
